#!/usr/bin/perl -w

my $usage='bam2bed bam bed'."\n";
unless(scalar(@ARGV)==2){print $usage; exit;}


my $rrr=rand();
$rrr=substr($rrr,2,6);



#`samtools sort -T /scratch/tmp/temp_bam.$rrr -n $ARGV[0]|bedtools bamtobed -bed12|fixChr|join_pairs|sort -k 6,6 -k 1,1 -k 2,2n -k 3,3n -k 11,11 -T /scratch/tmp -S 18G|collapseBED_no_sort_stdin|eightToZero > $ARGV[1]`;
`samtools sort -T /scratch/tmp/temp_bam.$rrr -n -O sam $ARGV[0]|rm_multimappers|samtools view -b -|bedtools bamtobed -bed12|fixChr|join_pairs|sort -k 6,6 -k 1,1 -k 2,2n -k 3,3n -k 11,11 -T /scratch/tmp -S 8G|collapseBED_no_sort_stdin|eightToZero > $ARGV[1]`;
